# Generated by Django 5.0.3 on 2024-03-09 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quesmodel_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 9, 4, 55, 18, 499811), verbose_name='Last Updated'),
        ),
    ]
